# Generated by Django 4.0.4 on 2022-04-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('updation_date', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
